### PR TITLE
Contributing guidelines

### PR DESCRIPTION
**Pull request by wtertinek**
# Update contributing guidelines, add analyzers+.editorconfig

## Description

1) The [contributing guidelines](https://github.com/wtertinek/Linq2Acad/blob/master/.github/CONTRIBUTING.md) should receive a major [update](https://github.com/wtertinek/Linq2Acad/blob/coding-guidelines/.github/CONTRIBUTING.md). The new version is derived from the Angular project's [guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md). The idea behind this update is to make Linq2Acad a more professional project.
2) Analyzers are a way to analyze a code base for consistent coding style. Analyzers and the appropriate .editorconfig file were added to ensure a uniform coding style for all contributions to this project.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Changes don't affect the runtime behavior, mostly code formatting

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by wtertinek** [comment]
Dear community,

what do you think about the new coding guidelines? Are they too extensive? Do they act as a deterrent to a less experienced developer who wants to contribute to the project? Or do you think it is good to have clear rules that are derived from a professional project?

I'm happy to hear your comments and feedback.

**Comment by benkoshy** [comment]
I"ll throw in my two cents: the ideal solution to most things should be drawn from practice / experience. In this case, the guidelines have been drawn from the experience of 1000s of commits on a large scale open source project. On the whole i think they are good, but would prefer to have deferred such guidelines till absolutely necessary. Will it stop someone from contributing? probably not......

coding styles conformity - etc i would welcome this.

**Comment by wtertinek** [comment]
Thanks for your comment Ben. Deferring the guidlines til absolutely necessary would mean, for a small project like Linq2Acad, that they most probably will not be used at all. Because for a small project there is not really a need for comprehensive guidlines.

On the other hand, I must say that I have already learned a lot through the Angular guidlines. I love the idea of conventional commits (which I saw the first time in your commits, Ben, and I liked it right away). So maybe new, more comprehensive guidlelines will bring someone else to learn something new as well.

**Comment by benkoshy** [comment]
If it's ready, why not merge this change?

**Comment by wtertinek** [comment]
I made a fixup commit to fix a spelling error and just realized that I should have squashed the commit manually. I thought this is done automatically when merging to the main branch. Learning never stops.

**Pull request merged**
