### PR TITLE
refactor: New project structure

### PR DESCRIPTION
**Pull request by wtertinek**
# Description

Finally managed to update the project structure. Working with the code base is painful. After adding/deleting AutoCAD version-specific files project files have to be updated manually. This PR introduces a project structure with one main C# project. Different AutoCAD versions target different framework versions and different versions of AutoCAD.Net.Core. This problem is addressed by introducing conditions into the project file.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactoring (non-breaking change which alters existing code)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Manual inspection of generated nupkg files

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by wtertinek** [comment]
@benkoshy I finally managed to update the project structure. Would be great if you could hae a look, maybe I overlooked something.

**Comment by benkoshy** [comment]
I'll study and get back to you.

**Comment by wtertinek** [comment]
Hi Ben,

thanks for having a look. Sorry, I should have been more specific. You don't have to look at the diffs, just check out the branch and open the solution. As it is difficult in the current project structure to make a change (because of the linked files and the many solution files), is it in the new structure easier to make a change? The fact that nine different AutoCAD versions are supported was represented in the old structure by nine different solutions, in the new structure it is one solution with 18 build configurations (nine Debug, nine Release). Are the many build configurations confusing? Just play around a bit and tell me what you think.

Thanks,
Wolfgang

**Comment by benkoshy** [comment]
@wtertinek sorry for the delay -  I have checked out the new branch - looks fine to me.

Would be interested in what you did, and how you did it?

**Comment by wtertinek** [comment]
Hi Ben,

thanks for you help. Happy to hear that everthing worked just fine for you.

The change was actually not that difficult, the only difficult thing was to find the right solution. ;) In the project file we now have two PropertyGroups for each AutoCAD version (one for *Debug* one for *Release*). These correspond to two build configurations in the solution. The PropertyGroups hold the specific configuration based on the AutoCAD version. The specific part for each AutoCAD version is a compiler costant *AutoCAD_20xx,* the TargetFrameworkVersion and a dedicated output folder. Here the two PropertyGroups for AutoCAD 2023:

```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug_2023|AnyCPU'">
  <DebugSymbols>true</DebugSymbols>
  <OutputPath>bin\Debug_2023\</OutputPath>
  <DefineConstants>DEBUG;TRACE;AutoCAD_2023</DefineConstants>
  <DocumentationFile>bin\Debug_2023\Linq2Acad.xml</DocumentationFile>
  <NoWarn>1591</NoWarn>
  <DebugType>full</DebugType>
  <PlatformTarget>AnyCPU</PlatformTarget>
  <LangVersion>7.3</LangVersion>
  <ErrorReport>prompt</ErrorReport>
  <TargetFrameworkVersion>v4.7</TargetFrameworkVersion>
</PropertyGroup>
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release_2023|AnyCPU' ">
  <DebugType>pdbonly</DebugType>
  <Optimize>true</Optimize>
  <OutputPath>bin\Release_2023\</OutputPath>
  <DefineConstants>TRACE;AutoCAD_2023</DefineConstants>
  <ErrorReport>prompt</ErrorReport>
  <WarningLevel>4</WarningLevel>
  <Prefer32Bit>false</Prefer32Bit>
  <NoWarn>1591</NoWarn>
  <DocumentationFile>bin\Release_2023\Linq2Acad.xml</DocumentationFile>
  <TargetFrameworkVersion>v4.7</TargetFrameworkVersion>
</PropertyGroup>
```

Now comes the tricky part: switching the AutoCAD.NET.Core Nuget package when switching the build configuration to another AutoCAD version. Solution: the project file offers kind of a switch-case statemet called *Choose* that allows for branching using *When* elements for each branch. A *When* element has a *Condition* attribute. So we create a *When* element for each AutoCAD version and in the condition we check the compiler constant AutoCAD_20xx:

```xml
<Choose>
  <When Condition="$(DefineConstants.Contains('AutoCAD_2015'))">
    <ItemGroup>
      <PackageReference Include="AutoCAD.NET.Core">
        <Version>20.0.1</Version>
        <ExcludeAssets>runtime</ExcludeAssets>
      </PackageReference>
    </ItemGroup>
  </When>

  <-- Other AutoCAD version go here -->

  <When Condition="$(DefineConstants.Contains('AutoCAD_2023'))">
    <ItemGroup>
      <PackageReference Include="AutoCAD.NET.Core">
        <Version>24.2.0</Version>
        <ExcludeAssets>runtime</ExcludeAssets>
        <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>
  </When>
</Choose>
```

The *Choose* element is a neat and powerful solution.

Finally, since we now have only one project file, the actual C# files are no longer links, they are now added directly to the project.

**Comment by benkoshy** [comment]
Hey Wolfgang,

I appreciate the explanation. Yet I do not understand from an overall view point:  What are the differences between the library which targets different AutoCAD versions? 

- Differences in .net - this evident in the commits. AutoCAD x uses .net 4.5 while version 5 uses .net 4.7.
- And then AutoCAD 20xx - makes reference to the respective 20xx ObjectARX dll? Is this correct?

Would be interested in fully understanding this?

chrs

**Comment by wtertinek** [comment]
Exactly. These are the only two differences.

**Comment by benkoshy** [comment]
If that is the case, then your work here is very valuable. It is a common problem - perhaps you would do very well to document it in your blog? Just throwing up ideas.

If only AutoDesk allowed for developers to target multiple releases with the same code base. It doesn't seem that difficult, given the API is fairly stable across releases. Perhaps they did this for commercial reasons?! In any you've done well to bite the bullet to solve it.

**Comment by wtertinek** [comment]
Thank you Ben! Yes, this is actually a very general topic that is applicable to projects other than AutoCAD projects as well. A blog post is a good idea, will put that on my todo list.

I have no idea why Autodesk does not provide at least some documentation on how to support multiple AutoCAD versions in a single project. I guess they don't see this as a problem they have to solve. Targeting one AutoCAD version, preferably always the latest, is the way to go for Autodesk.

**Comment by wtertinek** [comment]
If everything is OK so far I will merge the PR now. Thanks for your valuable support Ben!

**Pull request merged**
