### PR TITLE
Add AutoCAD 2024

### PR DESCRIPTION
**Pull request by wtertinek**
## Description

Adds new version of AutoCAD (2024).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

It has not been tested yet. I don't have access to AutoCAD 2024. I will provide a pre-release Nuget package for users to test it.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] Commit messages follow the [guidlines](.github/CONTRIBUTING.md#commit)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by wtertinek** [comment]
I've created a [NuGet package](https://www.nuget.org/packages/Linq2Acad-2024/1.0.0-rc1) for Linq2Acad-2024, but I don't have access to AutoCAD 2024. Would be great if someone could test that Linq2Acad-2024 works with AutoCAD 2024.

**Comment by benkoshy** [comment]
I can double check this the next time i do autocad development.

**Comment by benkoshy** [comment]
I now have autocad 2024. Except when I try to install via the pre-release this following materialises:

```c#
PM> NuGet\Install-Package Linq2Acad-2024 -Version 1.0.0-rc1

Attempting to gather dependency information for package 'Linq2Acad-2024.1.0.0-rc1' with respect to project 'Tekla-AutocadInterOp', targeting '.NETFramework,Version=v4.8'
Gathering dependency information took 7 ms
Attempting to resolve dependencies for package 'Linq2Acad-2024.1.0.0-rc1' with DependencyBehavior 'Lowest'
NuGet\Install-Package : Unable to find a version of 'AutoCAD.NET.Model' that is compatible with 'AutoCAD.NET.Core 24.2.0 constraint: AutoCAD.NET.Model (= 24.2.0)'.
At line:1 char:1
+ NuGet\Install-Package Linq2Acad-2024 -Version 1.0.0-rc1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

Not sure if I'm doing anything crazy on my end?

**Comment by wtertinek** [comment]
Hi Ben, sorry for not responding for so long. Were you able to solve the problem?

**Comment by benkoshy** [comment]
If you have no issues then I would recommend merging.

**Comment by benkoshy** [comment]
> Hi Ben, sorry for not responding for so long. Were you able to solve the problem?

No issues, I can appreciate / understand that time and resources are limited.

I myself have been unable to work on things -- until now - which is great.

**Pull request merged**
